import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/ui/sidebar";



export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="layout">
        <div>
        <SideBar />
        </div>
        <div className="mx-auto">
        {children}
        </div>
      
        
      </body>
    </html>
  );
}
